django_blog/django_blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
# from .import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace="posts"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .import views

urlpatterns = [
    url(r'^create$', views.post_create, name="create"),
    url(r'^$', views.post_list, name="list"), # Show all posts
    url(r'^(?P<id>\d+)$', views.post_detail, name="detail"), # Show specific post
    url(r'^(?P<id>\d+)/delete$', views.post_delete, name="delete"),
    url(r'^(?P<id>\d+)/edit$', views.post_update, name="update"), # Edit specific post
]

django_blog/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Post(models.Model):
    '''Models for Posts'''
    title = models.CharField(max_length=100)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return '{0}: {1}...'.format(self.title, self.content[:20])

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id})
        # return '/posts/{0}/'.format(self.id)

django_blog/posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image"
        ]

django_blog/posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from .models import Post
from .forms import PostForm

# CREATE A POST
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None) 
    if form.is_valid():
        instance = form.save(commit=False)
        # print(form.cleaned_data.get('title'))
        instance.save()

        messages.success(request, "Create Post Successful! ")
    else:
        messages.error(request, 'Error. Post not created.')

    context = {
        "title": 'Create a New Post',
        "form": form,
    }
    return render(request, "posts/create.html", context)

# SHOW A POST
def post_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)
    context = {
        "title": "Edit " + instance.title,
        "instance": instance
    }
    return render(request, 'posts/detail.html', context)

# SHOW ALL POSTS
def post_list(request):
    queryset = Post.objects.all()
    context = {
        "title": 'All Posts',
        "posts": queryset[::-1] # Reverse the order
    }
    return render(request, 'posts/list.html', context)

# UPDATE A POST
def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Edit successfully saved!")
        return HttpResponseRedirect(instance.get_absolute_url())
        
    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
        "edit": True,
    }
    return render(request, 'posts/create.html', context)

# DELETE A POST
def post_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "Successfully Deleted.")
    return redirect("posts:list")

django_blog/templates/includes/messages.html
{% if messages %} 
    {% for message in messages %}
        <p class="message">{{message}}</p>
    {% endfor %}
{% endif %}

django_blog/templates/posts/create.html
{% extends "shared/_layout.html" %}
{% block content %}

<div class="form-container">
    <form method="POST" action="" enctype="multipart/form-data" class="create-form">{% csrf_token %}
        <label for="{{form.title.id_for_label}}">New Title: </label>
        {{form.title}}

        <label for="{{form.content.id_for_label}}">New Content: </label>
        {{form.content}}

        <label for="{{form.content.id_for_label}}">Choose Image: </label>
        {{form.image}}

        {% if edit %}
            <input type="submit" value="Edit Post" class="button">
        {% else %}
            <input type="submit" value="Create Post" class="button">
        {% endif %}
    </form>
</div>

{% endblock content %}
    

django_blog/templates/posts/detail.html
{% extends "shared/_layout.html" %}

{% block content %}


<h2>{{instance.title}}</h2>

{% if instance.image %}
    <img src="{{instance.image.url}}" alt="">
{% endif %}

<p>{{instance.content}}</p>
<p>{{instance.updated}}</p>
<p>{{instance.timestamp}}</p>
<p>ID: {{instance.id}}</p>

<a href="{% url 'posts:update' id=instance.id  %}">Edit</a>
<a href="{% url 'posts:delete' id=instance.id  %}">Delete</a>

{% endblock content %}
    

django_blog/templates/posts/list.html
{% extends "shared/_layout.html" %}

{% block content %}

<div class="posts">
    {% for post in posts %}
    <div class="post">
        <div class="post-inner">
            {% if post.image %}
                <div class="image-container" style="background-image: url('{{post.image.url}}')">
                    {% comment %}<img src="{{post.image.url}}" alt="{{post.image.url}}">{% endcomment %}
                </div>
            {% endif %}
            <h3><a href="{% url 'posts:detail' id=post.id %}">{{ post.title }}</a></h3>
            <small>{{ post.timestamp | timesince:post.updated }}</small>

            <p>{{ post.content | truncatewords_html:40 }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}
 

django_blog/templates/shared/_layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Header -->
    <header class="container">
        <a href="{% url "posts:list" %}">Posts</a>
        <a href="{% url "posts:create" %}">Create a Post</a>
    </header>

    <!-- Messages -->
    {% include "includes/messages.html" %}

    <!-- Render Body -->
    <div class="container layout-container">
        {% comment %}<h1>{{title}}</h1>{% endcomment %}
        {% block content %}{% endblock content %}
    </div>

    <!-- Footer -->
    <footer>
        Nick Sam. Made with Django.
    </footer>

</body>
</html>